package model.gameController

class GameControllerTest extends munit.FunSuite{

  test("States") {
    val controller = new GameController
    assert(controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.fillHand()
    assert(!controller.inStart)
    assert(controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.selectedIndex("1 2 3 4")
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.play()
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.fillHand()
    assert(!controller.inStart)
    assert(controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.selectedIndex("1 2 3 4")
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.discard()
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(controller.inDiscard)
    assert(!controller.inFinish)
    controller.fillHand()
    assert(!controller.inStart)
    assert(controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.selectedIndex("1 2 3 4")
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.play()
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.fillHand()
    assert(!controller.inStart)
    assert(controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.selectedIndex("1 2 3 4")
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.play()
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(controller.inPlay)
    assert(!controller.inDiscard)
    assert(!controller.inFinish)
    controller.fillHand()
    assert(!controller.inStart)
    assert(!controller.inFillHand)
    assert(!controller.inSelectedIndex)
    assert(!controller.inPlay)
    assert(!controller.inDiscard)
    assert(controller.inFinish)

  }

}
